name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: uppg3
      id: uppg3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: uppg3
        setup-command: ''
        command: make test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        UPPG3_RESULTS: "${{steps.uppg3.outputs.result}}"
      with:
        runners: uppg3
